rails/blog/blog/config/routes.rb
# @Author: timaanonsen
# @Date:   12-27-2017 10:12::08
# @Filename: routes.rb
# @Last modified by:   timaanonsen
# @Last modified time: 12-28-2017 08:12::80




  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'welcome/index'

#  resources :articles
  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

rails/blog/blog/app/models/article.rb
# @Author: timaanonsen
# @Date:   12-28-2017 06:12::77
# @Filename: article.rb
# @Last modified by:   timaanonsen
# @Last modified time: 12-28-2017 09:12::57



class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
             length: { minimum: 5 }
end

rails/blog/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

rails/blog/blog/app/controllers/articles_controller.rb
# @Author: timaanonsen
# @Date:   12-27-2017 11:12::36
# @Filename: articles_controller.rb
# @Last modified by:   timaanonsen
# @Last modified time: 12-28-2017 09:12::12




 class ArticlesController < ApplicationController

   http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
      @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

rails/blog/blog/app/controllers/comments_controller.rb
# @Author: timaanonsen
# @Date:   12-28-2017 08:12::85
# @Filename: comments_controller.rb
# @Last modified by:   timaanonsen
# @Last modified time: 12-28-2017 09:12::36



class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

rails/blog/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails/blog/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/blog/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

rails/blog/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/blog/blog/app/views/comments/_comment.html.erb
<!--
@Author: timaanonsen
@Date:   12-28-2017 08:12::80
@Filename: _comment.html.erb
@Last modified by:   timaanonsen
@Last modified time: 12-28-2017 09:12::85
-->



<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

rails/blog/blog/app/views/comments/_form.html.erb
<!--
@Author: timaanonsen
@Date:   12-28-2017 08:12::71
@Filename: _form.html.erb
@Last modified by:   timaanonsen
@Last modified time: 12-28-2017 08:12::71
-->



<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

rails/blog/blog/app/views/welcome/index.html.erb
<!--
@Author: timaanonsen
@Date:   12-27-2017 10:12::67
@Filename: index.html.erb
@Last modified by:   timaanonsen
@Last modified time: 12-27-2017 12:12::22
-->



<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New article', new_article_path %>